// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var Verifier = artifacts.require('Verifier');
// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
contract('TestSquareVerifier', accounts => {

    describe('Verify Tx', function () {
        beforeEach(async function () { 
            this.contract = await Verifier.new({from: accounts[0] });

        })

        it('Correct verification', async function () { 
            let { proof, input } = require('../../zokrates/code/square/proof.json')
            let verified = await this.contract.verifyTx.call
                                (
                                    proof.A,
                                    proof.A_p,
                                    proof.B,
                                    proof.B_p,
                                    proof.C,
                                    proof.C_p,
                                    proof.H,
                                    proof.K,
                                    input
                                );
            assert.equal(verified, true, "Not verified correctly");
        })

    })
})