// Test if a new solution can be added for contract - SolnSquareVerifier

// Test if an ERC721 token can be minted for contract - SolnSquareVerifier



// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SolnSquareVerifier = artifacts.require('SolnSquareVerifier');
// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
contract('TestSolnSquareVerifier', accounts => {
    const account_one = accounts[0];
    const account_two = accounts[1];
    const { proof, input } = require('../../zokrates/code/square/proof.json')


    describe('Mint with square verifier', function () {
        beforeEach(async function () { 
            this.contract = await SolnSquareVerifier.new({from: account_one});
        })

        it('Minting', async function () { 
            await this.contract.mintNFT
                                (
                                    account_two,
                                    202,
                                    proof.A,
                                    proof.A_p,
                                    proof.B,
                                    proof.B_p,
                                    proof.C,
                                    proof.C_p,
                                    proof.H,
                                    proof.K,
                                    input
                               );
            let balance = await this.contract.balanceOf(account_two)
            assert.equal(balance, 1, 'Incorrect Balance')
        })

    })
})

